name: Check Coding Style
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-coding-syle:
    name: Check Coding Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Check EditorConfig
      - name: Install editorconfig-checker
        run: pip install editorconfig-checker
      - name: Check EditorConfig style
        run: ec

      # Check Commit Messages
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Check commits
        run: pre-commit run --hook-stage manual
