name: Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-coding-syle:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm run test
